openapi: 3.0.0
info:
  title: accounts-receivable-service
  version: '1.0'
  description: 請求サービス用の Public API です。
  contact:
    name: dummy
servers:
  - url: 'http://localhost:3000/accounts-receivable'
paths:
  /v1/acceptance-group/search:
    parameters: []
    post:
      summary: 検収グループ情報検索API
      operationId: searchAcceptanceGroupInternalV1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchAcceptanceGroupInternalResponseV1'
              examples:
                '@Example':
                  value:
                    recordCount: 1
                    acceptanceGroupInternalV1List:
                      - subsidiaryCode: JKT
                        acceptanceGroupCode: '860583'
                        incomingPaymentGroupCode: '860582'
                        acceptanceGroupNameNative: 精密
        '400':
          $ref: '#/components/responses/ErrorResponse'
      description: |-
        以下のマスタの情報を返却するAPIです。
          検収グループマスタ M_ACCEPTANCE_GROUP
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortby'
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Auth-Method
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Access-Token
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Api-Key
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-User-Type
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Auth-Id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Authorization
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Subsidiary-Code
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Language-Code
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Debug
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Operator-Id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Operator-Type
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Client-Program
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/x-datadog-trace-id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Cache-Control
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchAcceptanceGroupInternalRequestV1'
        description: 検収グループ情報検索APIのリクエスト電文
      tags:
        - AcceptanceGroupInternal
      x-channel:
        - internal
  /v1/acceptance-group/get:
    get:
      summary: 検収グループ情報取得API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAcceptanceGroupInternalResponseV1'
              examples:
                '@Example':
                  value:
                    recordCount: 1
                    acceptanceGroupInternalV1:
                      subsidiaryCode: JKT
                      acceptanceGroupCode: '860583'
                      incomingPaymentGroupCode: '860582'
                      acceptanceGroupNameNative: 精密
        '400':
          $ref: '#/components/responses/ErrorResponse'
      operationId: getAcceptanceGroupInternalV1
      description: |-
        以下のマスタの情報を返却するAPIです。
          検収グループマスタ M_ACCEPTANCE_GROUP
      parameters:
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Auth-Method
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Access-Token
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Api-Key
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-User-Type
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Auth-Id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Authorization
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Subsidiary-Code
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Language-Code
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Debug
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Operator-Id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Operator-Type
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Client-Program
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/x-datadog-trace-id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Cache-Control
        - schema:
            type: string
            minLength: 6
            maxLength: 6
          in: query
          name: acceptance_group_code
          description: 検収グループコード
          required: true
      tags:
        - AcceptanceGroupInternal
      x-channel:
        - internal
    parameters: []
  /v1/bill-to/search:
    post:
      summary: 売掛先情報検索API
      operationId: searchBillToInternalV1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchBillToInternalResponseV1'
              examples:
                '@Example':
                  value:
                    recordCount: 1
                    billToInternalV1List:
                      - subsidiaryCode: KOR
                        billToCode: '558814'
                        oldBillToCode: 'null'
                        arMainDepartment: KA
                        misumiPicCode: VO00
                        billToNameNative: 심보선
                        billToNameAbbreviationNative: 심보선
                        billToNameNativeForSearchIndex: 심보선
                        billToName: SHIM BO SEON
                        countryCode: '103'
                        languageCode: KOR
                        postalCode: 446-901
                        address1Native: 경기도 용인시 기흥구 원고매로 12
                        address2Native: (고매동) 리더스타워 6층
                        address3Native: 엠케이에스코리아
                        address4Native: 'null'
                        address1: GYEONGGI YONGINSI GIHEUNGGU
                        address2: WONGOMAERO12
                        address3: 'null'
                        address4: 'null'
                        invoiceSendDestinationDepartmentNameNative: 'null'
                        invoiceSendDestinationPicNative: 'null'
                        tel: 031-8021-1344
                        billToFax: 031-8005-9324
                        dunningToFax: 031-8005-9324
                        billToEmailAddressTo: bsshim@mksinst.com
                        billToEmailAddressCc: dummy1
                        dunningToEmailAddressTo: bsshim@mksinst.com
                        dunningToEmailAddressCc: dummy2
                        taxAccountStatementSendDestinationEmailAddress1: 'null'
                        taxAccountStatementSendDestinationEmailAddress2: '0'
                        tradeStopType: '0'
                        serviceStopType: '0'
                        acceptanceType: '0'
                        acceptanceGroupCode: '558814'
                        incoterms: DDP
                        paymentTerms: Credit Card
                        settlementMethod: CCD
                        paymentMeans: '50'
                        arClosingUnit: E
                        arClosingDay: 31
                        arPaymentMonth: 0
                        arPaymentDate: 1
                        arPaymentSiteFinal: 14
                        arPaymentSiteEarlyPaymentDiscount: 0
                        arEarlyIncomingPaymentDiscountRate: '0'
                        transferFee: '0'
                        customerAccountBankCode: 'null'
                        customerAccountType: '0'
                        customerAccountNumber: 'null'
                        customerAccountNameNativeAllowed: 'null'
                        transferAccountBankCode: 24106K
                        transferAccountType: '1'
                        transferAccountNumber: 140-003-465017
                        transferAccountName: (주)한국미스미
                        virtualAccountFlag: '0'
                        notePayableConditionAmount: '0'
                        notePayableConditionPaymentMonth: 0
                        notePayableConditionPaymentDate: 1
                        paymentSite: 0
                        invoiceSendType: '0'
                        invoiceViaType: '0'
                        invoiceViaTypeChild: 'null'
                        invoiceSendMedia: 'null'
                        dunningLetterSendType: '1'
                        dunningLetterSendMedia: AF
                        productNamePrintFlag: '0'
                        consumptionTaxMentionType: '0'
                        inExTaxType: '0'
                        ccyCode: KRW
                        rateTypeCode: KKRM
                        arDifficulty: 'null'
                        governmentUniformInvoiceType: '0'
                        companyRepresentativeNameNative: 'null'
                        arRemarks1: 'null'
                        arRemarks2: 'null'
                        arRemarks3: 'null'
                        arRemarks4: 'null'
                        arRemarks5: 'null'
                        invoiceRemarks1: 'null'
                        invoiceRemarks2: 'null'
                        invoiceRemarks3: 'null'
                        invoiceRemarks4: 'null'
                        gstPaymentPlace: 'null'
                        departmentName: 'null'
                        commissionerate: 'null'
                        stopReasonCode: 'null'
                        settlementMonth: 0
                        settlementClosingDay: 0
                        settlementSetting: '0'
                        cityCode: 'null'
                        invoiceOutputOrder: '0'
                        zenginCode: '0'
                        automaticTransferFlag: '0'
                        depositType: '1'
                        accountNumber: '1'
                        depositorNameKana: '1'
                        newCode: '1'
                        automaticTransferRegisterDate: '2019-08-24'
                        fbStopType: '1'
                        userTransferBank: 'null'
                        userTransferBranch: 'null'
                        arQctBaseCode: 'null'
                        closingDayFrontLoadingSettingType: '0'
                        industryType: '0'
                        channelType: '10'
                        eachBillRegister: 'null'
                        invoiceSlipOutputReportCode: 'null'
                        invoiceSummaryFlag: 'null'
                        customerStatementSendFlag: '1'
                        customerStatementSendMediaType: '3'
                        swiftCode: 'null'
                        withdrawalCollationAllowFlag: string
                        fax: 'null'
                        emailAddress: 'null'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      description: |-
        以下のマスタの情報を返却するAPIです。
          売掛先マスタ M_BILL_TO
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sortby'
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Auth-Method
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Access-Token
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Api-Key
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-User-Type
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Auth-Id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Authorization
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Subsidiary-Code
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Language-Code
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Debug
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Operator-Id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Operator-Type
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Client-Program
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/x-datadog-trace-id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Cache-Control
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchBillToInternalRequestV1'
        description: 売掛先情報検索APIのリクエスト電文
      tags:
        - BillToInternal
      x-channel:
        - internal
  /v1/bill-to/get:
    get:
      summary: 売掛先情報取得API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBillToInternalResponseV1'
              examples:
                '@Example':
                  value:
                    recordCount: 1
                    billToInternalV1:
                      subsidiaryCode: KOR
                      billToCode: '558814'
                      oldBillToCode: 'null'
                      arMainDepartment: KA
                      misumiPicCode: VO00
                      billToNameNative: 심보선
                      billToNameAbbreviationNative: 심보선
                      billToNameNativeForSearchIndex: 심보선
                      billToName: SHIM BO SEON
                      countryCode: '103'
                      languageCode: KOR
                      postalCode: 446-901
                      address1Native: 경기도 용인시 기흥구 원고매로 12
                      address2Native: (고매동) 리더스타워 6층
                      address3Native: 엠케이에스코리아
                      address4Native: 'null'
                      address1: GYEONGGI YONGINSI GIHEUNGGU
                      address2: WONGOMAERO12
                      address3: 'null'
                      address4: 'null'
                      invoiceSendDestinationDepartmentNameNative: 'null'
                      invoiceSendDestinationPicNative: 'null'
                      tel: 031-8021-1344
                      billToFax: 031-8005-9324
                      dunningToFax: 031-8005-9324
                      billToEmailAddressTo: bsshim@mksinst.com
                      billToEmailAddressCc: dummy1
                      dunningToEmailAddressTo: bsshim@mksinst.com
                      dunningToEmailAddressCc: dummy2
                      taxAccountStatementSendDestinationEmailAddress1: 'null'
                      taxAccountStatementSendDestinationEmailAddress2: '0'
                      tradeStopType: '0'
                      serviceStopType: '0'
                      acceptanceType: '0'
                      acceptanceGroupCode: '558814'
                      incoterms: DDP
                      paymentTerms: Credit Card
                      settlementMethod: CCD
                      paymentMeans: '50'
                      arClosingUnit: E
                      arClosingDay: 31
                      arPaymentMonth: 0
                      arPaymentDate: 1
                      arPaymentSiteFinal: 14
                      arPaymentSiteEarlyPaymentDiscount: 0
                      arEarlyIncomingPaymentDiscountRate: '0'
                      transferFee: '0'
                      customerAccountBankCode: 'null'
                      customerAccountType: '0'
                      customerAccountNumber: 'null'
                      customerAccountNameNativeAllowed: 'null'
                      transferAccountBankCode: 24106K
                      transferAccountType: '1'
                      transferAccountNumber: 140-003-465017
                      transferAccountName: (주)한국미스미
                      virtualAccountFlag: '0'
                      notePayableConditionAmount: '0'
                      notePayableConditionPaymentMonth: 0
                      notePayableConditionPaymentDate: 1
                      paymentSite: 0
                      invoiceSendType: '0'
                      invoiceViaType: '0'
                      invoiceViaTypeChild: 'null'
                      invoiceSendMedia: 'null'
                      dunningLetterSendType: '1'
                      dunningLetterSendMedia: AF
                      productNamePrintFlag: '0'
                      consumptionTaxMentionType: '0'
                      inExTaxType: '0'
                      ccyCode: KRW
                      rateTypeCode: KKRM
                      arDifficulty: 'null'
                      governmentUniformInvoiceType: '0'
                      companyRepresentativeNameNative: 'null'
                      arRemarks1: 'null'
                      arRemarks2: 'null'
                      arRemarks3: 'null'
                      arRemarks4: 'null'
                      arRemarks5: 'null'
                      invoiceRemarks1: 'null'
                      invoiceRemarks2: 'null'
                      invoiceRemarks3: 'null'
                      invoiceRemarks4: 'null'
                      gstPaymentPlace: 'null'
                      departmentName: 'null'
                      commissionerate: 'null'
                      stopReasonCode: 'null'
                      settlementMonth: 0
                      settlementClosingDay: 0
                      settlementSetting: '0'
                      cityCode: 'null'
                      invoiceOutputOrder: '0'
                      zenginCode: '0'
                      automaticTransferFlag: '0'
                      depositType: '1'
                      accountNumber: '1'
                      depositorNameKana: '1'
                      newCode: '1'
                      automaticTransferRegisterDate: '2019-08-24'
                      fbStopType: '1'
                      userTransferBank: 'null'
                      userTransferBranch: 'null'
                      arQctBaseCode: 'null'
                      closingDayFrontLoadingSettingType: '0'
                      industryType: '0'
                      channelType: '10'
                      eachBillRegister: 'null'
                      invoiceSlipOutputReportCode: 'null'
                      invoiceSummaryFlag: 'null'
                      customerStatementSendFlag: '1'
                      customerStatementSendMediaType: '3'
                      swiftCode: 'null'
                      withdrawalCollationAllowFlag: string
                      fax: 'null'
                      emailAddress: 'null'
                MASCR40010_1:
                  value:
                    recordCount: 1
                    billToInternalV1:
                      subsidiaryCode: KOR
                      billToCode: '558814'
                      oldBillToCode: 'null'
                      arMainDepartment: KA
                      misumiPicCode: VO00
                      billToNameNative: 심보선
                      billToNameAbbreviationNative: 심보선
                      billToNameNativeForSearchIndex: 심보선
                      billToName: SHIM BO SEON
                      countryCode: '103'
                      languageCode: KOR
                      postalCode: 446-901
                      address1Native: 경기도 용인시 기흥구 원고매로 12
                      address2Native: (고매동) 리더스타워 6층
                      address3Native: 엠케이에스코리아
                      address4Native: 'null'
                      address1: GYEONGGI YONGINSI GIHEUNGGU
                      address2: WONGOMAERO12
                      address3: 'null'
                      address4: 'null'
                      invoiceSendDestinationDepartmentNameNative: 'null'
                      invoiceSendDestinationPicNative: 'null'
                      tel: 031-8021-1344
                      billToFax: 031-8005-9324
                      dunningToFax: 031-8005-9324
                      billToEmailAddressTo: bsshim@mksinst.com
                      billToEmailAddressCc: dummy1
                      dunningToEmailAddressTo: bsshim@mksinst.com
                      dunningToEmailAddressCc: dummy2
                      taxAccountStatementSendDestinationEmailAddress1: 'null'
                      taxAccountStatementSendDestinationEmailAddress2: '0'
                      tradeStopType: '0'
                      serviceStopType: '0'
                      acceptanceType: '0'
                      acceptanceGroupCode: '558814'
                      incoterms: DDP
                      paymentTerms: Credit Card
                      settlementMethod: CCD
                      paymentMeans: '50'
                      arClosingUnit: E
                      arClosingDay: 31
                      arPaymentMonth: 0
                      arPaymentDate: 1
                      arPaymentSiteFinal: 14
                      arPaymentSiteEarlyPaymentDiscount: 0
                      arEarlyIncomingPaymentDiscountRate: '0'
                      transferFee: '0'
                      customerAccountBankCode: 'null'
                      customerAccountType: '0'
                      customerAccountNumber: 'null'
                      customerAccountNameNativeAllowed: 'null'
                      transferAccountBankCode: 24106K
                      transferAccountType: '1'
                      transferAccountNumber: 140-003-465017
                      transferAccountName: (주)한국미스미
                      virtualAccountFlag: '0'
                      notePayableConditionAmount: '0'
                      notePayableConditionPaymentMonth: 0
                      notePayableConditionPaymentDate: 1
                      paymentSite: 0
                      invoiceSendType: '0'
                      invoiceViaType: '0'
                      invoiceViaTypeChild: 'null'
                      invoiceSendMedia: 'null'
                      dunningLetterSendType: '1'
                      dunningLetterSendMedia: AF
                      productNamePrintFlag: '0'
                      consumptionTaxMentionType: '0'
                      inExTaxType: '0'
                      ccyCode: KRW
                      rateTypeCode: KKRM
                      arDifficulty: 'null'
                      governmentUniformInvoiceType: '0'
                      companyRepresentativeNameNative: 'null'
                      arRemarks1: 'null'
                      arRemarks2: 'null'
                      arRemarks3: 'null'
                      arRemarks4: 'null'
                      arRemarks5: 'null'
                      invoiceRemarks1: 'null'
                      invoiceRemarks2: 'null'
                      invoiceRemarks3: 'null'
                      invoiceRemarks4: 'null'
                      gstPaymentPlace: 'null'
                      departmentName: 'null'
                      commissionerate: 'null'
                      stopReasonCode: 'null'
                      settlementMonth: 0
                      settlementClosingDay: 0
                      settlementSetting: '0'
                      cityCode: 'null'
                      invoiceOutputOrder: '0'
                      zenginCode: '0'
                      automaticTransferFlag: '0'
                      depositType: '1'
                      accountNumber: '1'
                      depositorNameKana: '1'
                      newCode: '1'
                      automaticTransferRegisterDate: '2019-08-24'
                      fbStopType: '1'
                      userTransferBank: 'null'
                      userTransferBranch: 'null'
                      arQctBaseCode: 'null'
                      closingDayFrontLoadingSettingType: '0'
                      industryType: '0'
                      channelType: '10'
                      eachBillRegister: 'null'
                      invoiceSlipOutputReportCode: 'null'
                      invoiceSummaryFlag: 'null'
                      customerStatementSendFlag: '1'
                      customerStatementSendMediaType: '3'
                      swiftCode: 'null'
                      withdrawalCollationAllowFlag: string
                      fax: 'null'
                      emailAddress: 'null'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      operationId: getBillToInternalV1
      description: |-
        以下のマスタの情報を返却するAPIです。
          売掛先マスタ M_BILL_TO
      parameters:
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Auth-Method
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Access-Token
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Api-Key
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-User-Type
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Auth-Id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Authorization
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Subsidiary-Code
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Language-Code
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Debug
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Operator-Id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Operator-Type
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/X-Client-Program
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/x-datadog-trace-id
        - $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/parameters/Cache-Control
        - schema:
            type: string
            maxLength: 6
            example: '860583'
            minLength: 6
          in: query
          name: bill_to_code
          description: 売掛先コード
          required: true
      tags:
        - BillToInternal
      x-channel:
        - internal
    parameters: []
components:
  schemas:
    AcceptanceGroupInternalV1:
      title: AcceptanceGroupInternalV1
      type: object
      x-examples: {}
      description: 検収グループ情報
      properties:
        subsidiaryCode:
          type: string
          description: 現法コード
        acceptanceGroupCode:
          type: string
          description: 検収グループコード
        incomingPaymentGroupCode:
          type: string
          description: 入金グループコード
        acceptanceGroupNameNative:
          type: string
          description: 検収グループ名（現地語）
      required:
        - subsidiaryCode
        - acceptanceGroupCode
        - incomingPaymentGroupCode
        - acceptanceGroupNameNative
    BillToInternalV1:
      title: BillToInternalV1
      type: object
      description: 売掛先情報
      properties:
        subsidiaryCode:
          type: string
          description: 現法コード
        billToCode:
          type: string
          description: 売掛先コード
        oldBillToCode:
          type: string
          description: 旧売掛先コード
        arMainDepartment:
          type: string
          description: 売掛主管部署
        misumiPicCode:
          type: string
          description: ミスミ担当者コード
        billToNameNative:
          type: string
          description: 売掛先名（現地語）
        billToNameAbbreviationNative:
          type: string
          description: 売掛先名略称（現地語）
        billToNameNativeForSearchIndex:
          type: string
          description: 売掛先名（現地語検索用インデックス）
        billToName:
          type: string
          description: 売掛先名
        countryCode:
          type: string
          description: 国コード
        languageCode:
          type: string
          description: 言語コード
        postalCode:
          type: string
          description: 郵便番号
        address1Native:
          type: string
          description: 住所1（現地語）
        address2Native:
          type: string
          description: 住所2（現地語）
        address3Native:
          type: string
          description: 住所3（現地語）
        address4Native:
          type: string
          description: 住所4（現地語）
        address1:
          type: string
          description: 住所1
        address2:
          type: string
          description: 住所2
        address3:
          type: string
          description: 住所3
        address4:
          type: string
          description: 住所4
        invoiceSendDestinationDepartmentNameNative:
          type: string
          description: 請求書送付先部課名（現地語）
        invoiceSendDestinationPicNative:
          type: string
          description: 請求書送付先担当者（現地語）
        tel:
          type: string
          description: 電話番号
        billToFax:
          type: string
          description: 売掛先FAX番号
        dunningToFax:
          type: string
          description: 督促先FAX番号
        billToEmailAddressTo:
          type: string
          description: 売掛先メールアドレス（TO）
        billToEmailAddressCc:
          type: string
          description: 売掛先メールアドレス（CC）
        dunningToEmailAddressTo:
          type: string
          description: 督促先メールアドレス（TO）
        dunningToEmailAddressCc:
          type: string
          description: 督促先メールアドレス（CC）
        taxAccountStatementSendDestinationEmailAddress1:
          type: string
          description: 税金計算書送付先メールアドレス1
        taxAccountStatementSendDestinationEmailAddress2:
          type: string
          description: 税金計算書送付先メールアドレス2
        tradeStopType:
          type: string
          description: 取引停止区分
        serviceStopType:
          type: string
          description: サービス停止区分
        acceptanceType:
          type: string
          description: 検収区分
        acceptanceGroupCode:
          type: string
          description: 検収グループコード
        incoterms:
          type: string
          description: インコタームズ
        paymentTerms:
          type: string
          description: 支払条件
        settlementMethod:
          type: string
          description: 決済形態
        paymentMeans:
          type: string
          description: 支払手段
        arClosingUnit:
          type: string
          description: 売掛金締め単位
        arClosingDay:
          description: 売掛金締日
          type: integer
        arPaymentMonth:
          description: 売掛金支払月
          type: integer
        arPaymentDate:
          description: 売掛金支払日
          type: integer
        arPaymentSiteFinal:
          description: 売掛金支払サイト_最終
          type: integer
        arPaymentSiteEarlyPaymentDiscount:
          description: 売掛金支払サイト_早割
          type: integer
        arEarlyIncomingPaymentDiscountRate:
          type: string
          description: 売掛金早期入金割引率
          format: decimal
        transferFee:
          type: string
          description: 振込手数料
        customerAccountBankCode:
          type: string
          description: 顧客口座銀行コード
        customerAccountType:
          type: string
          description: 顧客口座区分
        customerAccountNumber:
          type: string
          description: 顧客口座番号
        customerAccountNameNativeAllowed:
          type: string
          description: 顧客口座人名（現地語可）
        transferAccountBankCode:
          type: string
          description: 振込口座銀行コード
        transferAccountType:
          type: string
          description: 振込口座区分
        transferAccountNumber:
          type: string
          description: 振込口座番号
        transferAccountName:
          type: string
          description: 振込口座人名
        virtualAccountFlag:
          type: string
          description: 仮想口座フラグ
        notePayableConditionAmount:
          type: string
          description: 手形条件（金額）
          format: decimal
        notePayableConditionPaymentMonth:
          description: 手形条件（支払月）
          type: integer
        notePayableConditionPaymentDate:
          type: integer
          description: 手形条件（支払日）
        paymentSite:
          type: integer
          description: 支払サイト
        invoiceSendType:
          type: string
          description: 請求書送付区分
        invoiceViaType:
          type: string
          description: 請求書経由区分
        invoiceViaTypeChild:
          type: string
          description: 請求書経由区分_子
        invoiceSendMedia:
          type: string
          description: 請求書送付媒体
        dunningLetterSendType:
          type: string
          description: 督促状送付区分
        dunningLetterSendMedia:
          type: string
          description: 督促状送付媒体
        productNamePrintFlag:
          type: string
          description: 商品名印字フラグ
        consumptionTaxMentionType:
          type: string
          description: 消費税記載区分
        inExTaxType:
          type: string
          description: 内税外税区分
        ccyCode:
          type: string
          description: 通貨コード
        rateTypeCode:
          type: string
          description: レートタイプコード
        arDifficulty:
          type: string
          description: 売掛難易度
        governmentUniformInvoiceType:
          type: string
          description: 統一発票区分
        companyRepresentativeNameNative:
          type: string
          description: 会社代表者名（現地語）
        arRemarks1:
          type: string
          description: 売掛注釈1
        arRemarks2:
          type: string
          description: 売掛注釈2
        arRemarks3:
          type: string
          description: 売掛注釈3
        arRemarks4:
          type: string
          description: 売掛注釈4
        arRemarks5:
          type: string
          description: 売掛注釈5
        invoiceRemarks1:
          type: string
          description: INVOICE注釈1
        invoiceRemarks2:
          type: string
          description: INVOICE注釈2
        invoiceRemarks3:
          type: string
          description: INVOICE注釈3
        invoiceRemarks4:
          type: string
          description: INVOICE注釈4
        gstPaymentPlace:
          type: string
          description: 物品税管理地
        departmentName:
          type: string
          description: 部署名
        commissionerate:
          type: string
          description: 物品税管理区
        stopReasonCode:
          type: string
          description: 停止理由コード
        settlementMonth:
          description: 決算月
          type: integer
        settlementClosingDay:
          description: 決算締切日
          type: integer
        settlementSetting:
          type: string
          description: 決算設定
        cityCode:
          type: string
          description: 市町村コード
        invoiceOutputOrder:
          type: string
          description: 請求書出力順
        zenginCode:
          type: string
          description: 全銀コード
        automaticTransferFlag:
          type: string
          description: 自動振替フラグ
        depositType:
          type: string
          description: 預金種類
        accountNumber:
          type: string
          description: 口座番号
        depositorNameKana:
          type: string
          description: 預金者名（カナ）
        newCode:
          type: string
          description: 新規コード
        automaticTransferRegisterDate:
          type: string
          description: 自動振替登録日
          format: date
        fbStopType:
          type: string
          description: FB停止区分
        userTransferBank:
          type: string
          description: ユーザー振込銀行
        userTransferBranch:
          type: string
          description: ユーザー振込支店
        arQctBaseCode:
          type: string
          description: 売掛QCT拠点コード
        closingDayFrontLoadingSettingType:
          type: string
          description: 締日前倒し設定区分
        industryType:
          type: string
          description: 業種区分
        channelType:
          type: string
          description: 経路区分
        eachBillRegister:
          type: string
          description: 都度請求登録
        invoiceSlipOutputReportCode:
          type: string
          description: 請求書伝発帳票コード
        invoiceSummaryFlag:
          type: string
          description: 請求書まとめフラグ
        customerStatementSendFlag:
          type: string
          description: カスタマーステートメント送付対象フラグ
        customerStatementSendMediaType:
          type: string
          description: カスタマーステートメント送付媒体区分
        swiftCode:
          type: string
          description: SWIFTコード
        withdrawalCollationAllowFlag:
          type: string
          description: 取崩し照合許可フラグ
        fax:
          type: string
          description: FAX番号
        emailAddress:
          type: string
          description: メールアドレス
      required:
        - subsidiaryCode
        - billToCode
        - billToName
        - countryCode
        - languageCode
        - address1Native
        - tradeStopType
        - serviceStopType
        - acceptanceType
        - acceptanceGroupCode
        - paymentTerms
        - settlementMethod
        - paymentMeans
        - transferFee
        - invoiceSendType
        - dunningLetterSendType
        - productNamePrintFlag
        - consumptionTaxMentionType
        - inExTaxType
        - ccyCode
        - rateTypeCode
        - settlementSetting
        - invoiceOutputOrder
        - automaticTransferFlag
        - fbStopType
        - closingDayFrontLoadingSettingType
    SearchAcceptanceGroupInternalResponseV1:
      title: SearchAcceptanceGroupInternalResponseV1
      type: object
      description: 検収グループ情報検索APIのレスポンス電文
      properties:
        recordCount:
          type: integer
          description: レコード件数
        acceptanceGroupInternalV1List:
          type: array
          description: 検収グループ情報リスト
          items:
            $ref: '#/components/schemas/AcceptanceGroupInternalV1'
      required:
        - recordCount
    GetAcceptanceGroupInternalResponseV1:
      title: GetAcceptanceGroupInternalResponseV1
      type: object
      description: 検収グループ情報取得APIのレスポンス電文
      properties:
        recordCount:
          type: integer
          description: レコード件数
        acceptanceGroupInternalV1:
          $ref: '#/components/schemas/AcceptanceGroupInternalV1'
      required:
        - recordCount
    SearchBillToInternalResponseV1:
      title: SearchBillToInternalResponseV1
      type: object
      description: 売掛先情報検索APIのレスポンス電文
      properties:
        recordCount:
          type: integer
          description: レコード件数
        billToInternalV1List:
          type: array
          description: 売掛先情報リスト
          items:
            $ref: '#/components/schemas/BillToInternalV1'
      required:
        - recordCount
    GetBillToInternalResponseV1:
      title: GetBillToInternalResponseV1
      type: object
      description: 売掛先情報取得APIのレスポンス電文
      properties:
        recordCount:
          type: integer
          description: レコード件数
        billToInternalV1:
          $ref: '#/components/schemas/BillToInternalV1'
      required:
        - recordCount
    SearchBillToInternalRequestV1:
      title: SearchBillToInternalRequestV1
      type: object
      description: 売掛先情報検索APIのリクエスト項目電文
      properties:
        billToCodeList:
          type: array
          maxLength: 6
          minLength: 6
          description: 売掛先情報検索APIのリクエスト項目電文詳細の売掛先コード情報リスト
          items:
            $ref: '#/components/schemas/SearchBillToInternalRequestV1BillToCode'
        billToCodeFrom:
          type: string
          description: 売掛先コード（From）
          minLength: 6
          maxLength: 6
        billToCodeTo:
          type: string
          description: 売掛先コード（To）
          minLength: 6
          maxLength: 6
        billToNameNative:
          type: string
          description: 売掛先名（現地語）
          minLength: 1
          maxLength: 60
        billToName:
          type: string
          description: 売掛先名
          minLength: 1
          maxLength: 60
        acceptanceGroupCodeList:
          type: array
          maxLength: 6
          minLength: 6
          description: 売掛先情報検索APIのリクエスト項目電文詳細の検収グループコード情報リスト
          items:
            $ref: '#/components/schemas/SearchBillToInternalRequestV1AcceptanceGroupCode'
    SearchAcceptanceGroupInternalRequestV1:
      title: SearchAcceptanceGroupInternalRequestV1
      type: object
      description: 検収グループ情報検索APIのリクエスト項目電文
      properties:
        acceptanceGroupCodeList:
          type: array
          description: 検収グループ情報検索APIのリクエスト項目電文詳細の検収グループコード情報リスト
          items:
            $ref: '#/components/schemas/SearchAcceptanceGroupInternalRequestV1AcceptanceGroupCode'
        incomingPaymentGroupCodeList:
          type: array
          description: 検収グループ情報検索APIのリクエスト項目電文詳細の入金グループコード情報リスト
          items:
            $ref: '#/components/schemas/SearchAcceptanceGroupInternalRequestV1IncomingPaymentGroupCode'
        incomingPaymentGroupCodeFrom:
          type: string
          description: 入金グループコード（From）
          minLength: 6
          maxLength: 6
        incomingPaymentGroupCodeTo:
          type: string
          description: 入金グループコード（To）
          minLength: 6
          maxLength: 6
    SearchAcceptanceGroupInternalRequestV1AcceptanceGroupCode:
      title: SearchAcceptanceGroupInternalRequestV1AcceptanceGroupCode
      type: object
      description: 検収グループ情報検索APIのリクエスト項目電文詳細の検収グループコード情報
      properties:
        acceptanceGroupCode:
          type: string
          description: 検収グループコード
          maxLength: 6
          minLength: 6
      required:
        - acceptanceGroupCode
    SearchAcceptanceGroupInternalRequestV1IncomingPaymentGroupCode:
      title: SearchAcceptanceGroupInternalRequestV1IncomingPaymentGroupCode
      type: object
      description: 検収グループ情報検索APIのリクエスト項目電文詳細の入金グループコード情報
      properties:
        incomingPaymentGroupCode:
          type: string
          description: 入金グループコード
          maxLength: 6
          minLength: 6
      required:
        - incomingPaymentGroupCode
    SearchBillToInternalRequestV1BillToCode:
      title: SearchBillToInternalRequestV1BillToCode
      type: object
      description: 売掛先情報検索APIのリクエスト項目電文詳細の売掛先コード情報
      properties:
        billToCode:
          type: string
          description: 売掛先コード
          maxLength: 6
          minLength: 6
          example: '860583'
      required:
        - billToCode
    SearchBillToInternalRequestV1AcceptanceGroupCode:
      title: SearchBillToInternalRequestV1AcceptanceGroupCode
      type: object
      description: 売掛先情報検索APIのリクエスト項目電文詳細の検収グループコード情報
      properties:
        acceptanceGroupCode:
          type: string
          description: 検収グループコード
          maxLength: 6
          minLength: 6
      required:
        - acceptanceGroupCode
  responses:
    ErrorResponse:
      description: エラーレスポンス
      content:
        application/json:
          schema:
            $ref: ../../misumi-api-spec/common-spec/common-spec.yaml#/components/schemas/Error1
          examples:
            '@Example':
              value:
                target: ''
                code: SYS00003
                argumentList: []
                message: Constraint violation
                detailList:
                  - target: 'acceptanceGroupCodeList[0].acceptanceGroupCode'
                    code: SYS03113
                    argumentList: []
                    message: 'acceptanceGroupCodeList[0].acceptanceGroupCode must not be null, blank, or empty'
                    detailList: []
                  - target: 'billToCodeList[0].billToCode'
                    code: SYS03113
                    argumentList: []
                    message: 'billToCodeList[0].billToCode must not be null, blank, or empty'
                    detailList: []
  parameters:
    offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
      description: 取得開始位置
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
      description: 返却件数
    sortby:
      name: sortby
      in: query
      required: false
      schema:
        type: string
        minLength: 1
      description: ソート順
tags:
  - name: AcceptanceGroupInternal
  - name: BillToInternal
